name: Build AntiAFK-RBX

on:
  push:
    branches: [preview]
    tags: ['v*']

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Release]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution
        run: msbuild AntiAFK-RBX.sln /p:Configuration=${{ matrix.configuration }} /p:Platform=x64 /m

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AntiAFK-RBX-${{ matrix.configuration }}
          path: x64/${{ matrix.configuration }}/*.exe


